# Generated by Django 3.2 on 2022-09-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
