# Generated by Django 3.2 on 2022-09-20 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist_name', models.TextField(blank=True, null=True)),
                ('track_name', models.TextField(blank=True, null=True)),
                ('track_id', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('market', models.TextField(blank=True, null=True)),
                ('track_popularity', models.IntegerField(blank=True, null=True)),
                ('artist_id', models.TextField(blank=True, null=True)),
                ('danceability', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('key', models.IntegerField(blank=True, null=True)),
                ('loudness', models.FloatField(blank=True, null=True)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('speechiness', models.FloatField(blank=True, null=True)),
                ('acousticness', models.FloatField(blank=True, null=True)),
                ('instrumentalness', models.FloatField(blank=True, null=True)),
                ('liveness', models.FloatField(blank=True, null=True)),
                ('valence', models.FloatField(blank=True, null=True)),
                ('tempo', models.FloatField(blank=True, null=True)),
                ('time_signature', models.IntegerField(blank=True, null=True)),
                ('videoid', models.TextField(blank=True, db_column='videoId', null=True)),
                ('like_users', models.ManyToManyField(related_name='favorite_musics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
