# Generated by Django 3.2 on 2022-09-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_auto_20220922_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='sticker_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='stickers.stickerpack'),
        ),
    ]
