# Generated by Django 3.2 on 2022-09-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarysticker',
            name='sticker',
        ),
    ]
