# Generated by Django 3.2 on 2022-09-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='context',
            new_name='content',
        ),
    ]
