# Generated by Django 3.2 on 2022-09-23 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_auto_20220922_1505'),
        ('diaries', '0002_remove_diarysticker_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarysticker',
            name='sticker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stickers.sticker'),
            preserve_default=False,
        ),
    ]
