# Generated by Django 3.2 on 2022-09-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_diarysticker_sticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
