# Generated by Django 3.2 on 2022-09-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_auto_20220923_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='diary',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DiaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=50)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaries.diary')),
            ],
        ),
        migrations.AddConstraint(
            model_name='diaryimage',
            constraint=models.UniqueConstraint(fields=('image_id', 'diary'), name='unique_image'),
        ),
    ]
