# Generated by Django 3.2 on 2022-09-24 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0006_auto_20220924_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
