# Generated by Django 3.2 on 2022-09-24 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0008_auto_20220924_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryimage',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diaries.diary'),
        ),
        migrations.AlterField(
            model_name='diarymusic',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='diaries.diary'),
        ),
        migrations.AlterField(
            model_name='diarysticker',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='diaries.diary'),
        ),
    ]
