# Generated by Django 3.2 on 2022-09-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0009_auto_20220924_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryimage',
            old_name='image_id',
            new_name='image_url',
        ),
    ]
