# Generated by Django 3.2 on 2022-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0010_rename_image_id_diaryimage_image_url'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diaryimage',
            name='unique_image',
        ),
        migrations.AddConstraint(
            model_name='diaryimage',
            constraint=models.UniqueConstraint(fields=('image_url', 'diary'), name='unique_image'),
        ),
    ]
