# Generated by Django 3.2 on 2022-09-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0011_auto_20220924_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
