# Generated by Django 3.2 on 2022-09-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0012_diary_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='created_date',
            field=models.CharField(default='2022-09-24', max_length=20),
            preserve_default=False,
        ),
    ]
