# Generated by Django 3.2 on 2022-09-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0013_diary_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_id',
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diaryimage',
            name='image_url',
            field=models.CharField(max_length=256),
        ),
    ]
