# Generated by Django 3.2 on 2022-09-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0015_diarymusic_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarymusic',
            name='like',
        ),
    ]
