# Generated by Django 3.2 on 2022-09-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0016_remove_diarymusic_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarymusic',
            name='like',
            field=models.BinaryField(default=False),
        ),
    ]
