# Generated by Django 3.2 on 2022-10-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0017_diarymusic_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymusic',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
